name: Build LaTeX document
on:
  push:
    paths-ignore:
      - '*.pdf'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_shell_escape: true
      - name: Commit report
        run: |
          git config --global user.name 'Mansin-ITU'
          git config --global user.email 'beth@itu.dk'
          git add main.pdf
          git commit -m "Automated pdf"
          git push
